name: Horoscope Scraper Scheduler

on:
  schedule:
    - cron: '40 4 * * *'  # Run at 4:40 AM Baghdad time
    - cron: '0 5 * * *'   # Run at 5:00 AM Baghdad time
    - cron: '0 9 * * *'   # Run at 9:00 AM Baghdad time
  workflow_dispatch:      # Allow manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon requests pytz celery redis pillow
          pip install undetected-chromedriver webdriver-manager
          
      - name: Create directories
        run: |
          mkdir -p data/images
          
      - name: Debug environment
        run: |
          echo "Python version:"
          python --version
          echo "Current directory:"
          pwd
          echo "Directory listing:"
          ls -la
          
      - name: Fix Telegram session
        env:
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: |
          echo "Creating session file..."
          echo "$TELEGRAM_SESSION" > session_base64.txt
          base64 -d session_base64.txt > the_alabrage_session.session || echo "base64 decode failed"
          echo "Session file size: $(stat -c%s the_alabrage_session.session || echo 'unknown')"
          
      - name: Create simple Telegram session
        run: |
          python -c "
import json
with open('telegram_config.json', 'w') as f:
    json.dump({
        'api_id': '${{ secrets.TELEGRAM_API_ID }}',
        'api_hash': '${{ secrets.TELEGRAM_API_HASH }}',
        'phone': '${{ secrets.TELEGRAM_PHONE }}'
    }, f)
          "
          
      - name: Run horoscope scraper
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          python horoscope_scraper_publisher.py --scrape