name: Horoscope Scraper Scheduler

on:
  schedule:
    - cron: '40 4 * * *'  # Run at 4:40 AM Baghdad time
    - cron: '0 5 * * *'   # Run at 5:00 AM Baghdad time
    - cron: '0 9 * * *'   # Run at 9:00 AM Baghdad time
  workflow_dispatch:      # Allow manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon requests pytz celery redis pillow
          
      - name: Install Chrome and related tools
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install webdriver-manager undetected-chromedriver
          
      - name: Create data directories
        run: |
          mkdir -p data/images
          
      - name: Download horoscope images
        run: |
          # Download sample images if needed (or you can commit them to your repo)
          # This is a placeholder - you'd need to add actual image download commands
          echo "Downloading horoscope images..."
          
      - name: Prepare session file
        env:
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
        run: |
          # Create the telegram session file from the secret
          echo "$TELEGRAM_SESSION" > the_alabrage_session.session
          
      - name: Run horoscope scraper
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE: ${{ secrets.TELEGRAM_PHONE }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          python horoscope_scraper_publisher.py --scrape